#!/bin/sh

mkdir -p temp
sc source/main.sc temp/main.c

if [ $1 ]
then
  astyle temp/main.c
fi

gcc -std=gnu99 -Wall -Werror -Wfatal-errors -o3 -shared -fpic \
$(guile-config compile) $(guile-config link) -lfuse -o temp/libguile-fuse.so \
temp/main.c -Wl,--version-script=other/export && chmod -R 755 temp
