#!/bin/sh -e

prefix="$1"

mkdir -pm 755 "$prefix/usr/lib" "$prefix/usr/share/guile/site"
cp "temp/libguile-fuse.so" "$prefix/usr/lib/libguile-fuse.so"
chmod 644 /usr/lib/libguile-fuse.so
cp "source/scheme/fuse.scm" "$prefix/usr/share/guile/site/fuse.scm"
chmod 644 /usr/share/guile/site/fuse.scm
